### ISSUE TITLE
login fails since two days ago

### ISSUE THREAD

**Issue by guy-BW** [mitch-dc/volkswagen_we_connect_id#148]
## Version of the custom_component

 0.1.3

## Installation method (hacs / manual)

has install on pi-4 installed from image file onto SD card.

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

Since two days ago, I'm getting an error when HA is attempting to login to the VW connect.. It was working just fine..

## Debug log

Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47 
Integration: Volkswagen We Connect ID 
First occurred: 17:35:33 (2 occurrences) 
Last logged: 17:35:33

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

```text

Add your logs here.

```

**Comment by The-Fatal** [comment]
having the same error:

`Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'`

**Comment by BaukeDeVries** [comment]
Same problem here, since yeaterday. Rebooting/reloading has no effect.

**Comment by roppenheimer** [comment]
I am getting the following:

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by PalmSwe** [comment]
Same problem as in issue #143

**Comment by mwevromans** [comment]
also issue here, seems a bit like the same

2023-02-28 07:18:27.298 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ID4 for volkswagen_we_connect_id
File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
2023-02-28 21:26:02.944 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ID4 for volkswagen_we_connect_id
File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry

**Comment by markgilbert-git** [comment]
I'm getting the same error with a really similar error log entry

**Comment by firefox159** [comment]
same

**Comment by ArveVM** [comment]
> Same problem as in issue #143

Guess not the same issue :(
#143 was "You have to login at myvolkswagen.de and accept the terms and conditions"
I did that - and it worked for a couple of days,,, 

Now i get this error- which i guess is different from #143 but same as Guy-BW is starting this post with?

I can log into wv web-interface and the ID-app with my credentials, so they work just fine.
Have tried to add the integration in my test-env, but it is not getting past the username/password/submit-dialogue,,   :(


Many thanks to Mitch & contributors for the integration,, was getting used to having soc in HA :)
- hopfully they will bring it back in order :)


```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47
Integration: Volkswagen We Connect ID
First occurred: February 28, 2023 at 10:47:46 (2 occurrences)
Last logged: February 28, 2023 at 11:50:08

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

**Comment by mitch-dc** [comment]
Fixed in https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.1.4 but you also need to 
update Homeassistant to at least version 2023.3.0.

**Comment by strutings** [comment]
Still missing SoC and range among other entities after the update. Still on car version 2.4. Is the latest version compatible with pre 3.0 version?

**Comment by mikrohard** [comment]
The required pull request wasn't included in home assistant 2023.3.0. It's currently just in the dev branch. You'll have to wait for the next release.

**Comment by strutings** [comment]
Will a manual update to request 2.28.2 fix this issue?
