### ISSUE TITLE
Dependency error after 0.1.4 upgrade

### ISSUE THREAD

**Issue by whohencode** [mitch-dc/volkswagen_we_connect_id#149]
## Version of the custom_component
0.1.4

## Installation method (hacs / manual)
Hacs

## Installation method of hass (venv, docker, hassio,...) 
Hass in docker

## Configuration
```
No config changed, only upgradeed to 0.1.4
```

## Describe the bug

Dependency error after upgrading from 0.1.3 to 0.1.4 with ha 2023.2.5

Requirements for volkswagen_we_connect_id not found: ['weconnect==0.54.1'].

## Debug log

Debugging gave no more than the log.

```
2023-02-28 20:48:44.924 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration volkswagen_we_connect_id: Requirements for volkswagen_we_connect_id not found: ['weconnect==0.54.1'].

```

**Comment by Enough64** [comment]
Me too. However I get

`2023-02-28 20:53:17.074 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: pip install --upgrade pip`

**Comment by aveXcaesar** [comment]
Same for me in HA installed on a RaspberryPi

**Comment by mitch-dc** [comment]
I know. Got the same issue, not sure why this happens. 

Need more time to investigate, hope i can find someone with more python knowledge.

**Comment by sttaelma** [comment]
i had to manually run command "pip install weconnect --upgrade" from within the homeassistant docker to get the python library "weconnect" to be upgraded to v0.54.1 - v0.51.0 was still installed.
i'm unsure how to manage these python libraries from within the homeassistant gui

i did a test after, but seems to api is not responding (configuration keeps running)

**Comment by tillstaff** [comment]
> I know. Got the same issue, not sure why this happens.
> 
> Need more time to investigate, hope i can find someone with more python knowledge.

There is a problem with the new library requirements of weconnect 0.54.1.

homeassistant 2023.2.5 requires requests==2.28.1, but weconnect requires requests 2.28.2 which is incompatible.

```
bash-5.1# pip3 install weconnect==0.54.1
Collecting weconnect==0.54.1
  Downloading weconnect-0.54.1-py3-none-any.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.7/156.7 kB 3.0 MB/s eta 0:00:00
Collecting requests~=2.28.2
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: oauthlib~=3.2.2 in /usr/local/lib/python3.10/site-packages (from weconnect==0.54.1) (3.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests~=2.28.2->weconnect==0.54.1) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests~=2.28.2->weconnect==0.54.1) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests~=2.28.2->weconnect==0.54.1) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests~=2.28.2->weconnect==0.54.1) (3.4)
Installing collected packages: requests, weconnect
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
  Attempting uninstall: weconnect
    Found existing installation: weconnect 0.51.0
    Uninstalling weconnect-0.51.0:
      Successfully uninstalled weconnect-0.51.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nuheat 1.0.0 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.
ibm-watson 5.2.2 requires websocket-client==1.1.0, but you have websocket-client 1.5.1 which is incompatible.
homeassistant 2023.2.5 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.
Successfully installed requests-2.28.2 weconnect-0.54.1
```

**Comment by mitch-dc** [comment]
Fixed in https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.1.4 but you also need to 
update Homeassistant to at least version 2023.3.0.

**Comment by firefox159** [comment]
Just wondering - 2023.3 does not show to be available on my HA yet...

**Comment by TravisWilder** [comment]
Home Assistant 2023.3.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230301.0 - latest


Still get the error
Setup failed for custom integration volkswagen_we_connect_id: Requirements for volkswagen_we_connect_id not found: ['weconnect==0.54.1'].

Does this need to be installed manually?

**Comment by svenkessler** [comment]
Also updated to Home Assistant 2023.3.0 and 0.1.4
Got the same error mentioned here, so tried to delete the integration and re-added it.
Now I got this error when trying to activate:

`Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip`

**Comment by PaulProjects** [comment]
I got similar issues:
first occurence of the error:
volkswagen_we_connect_id version 0.1.3 - the integration never finished starting up
 
-updated volkswagen_we_connect_id (0.1.4) and HA ( Home Assistant 2023.3.0 Supervisor 2023.01.1 Operating System 9.5 Frontend 20230301.0 - latest) and got this error message:

Setup failed for custom integration volkswagen_we_connect_id: Requirements for volkswagen_we_connect_id not found: ['weconnect==0.54.1'].

- Removed integration, restart, redownloaded integration, restart, added integration and got this error:
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

EVCC fixed this issue by changing the Base and Login URL (https://github.com/evcc-io/evcc/commit/afcb5899a4bc1870f8ce2dde1524586ae1722cff)

**Comment by robinostlund** [comment]
Found a solution for the sensor issue.

This:
`
    VolkswagenIdEntityDescription(
        key="chargePower_kW",
        name="Charge Power",
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.energy,
        state_class=measurement,
        value=lambda data: data["charging"]["chargingStatus"].chargePower_kW.value,
    ),
`

Needs to be this:

`
    VolkswagenIdEntityDescription(
        key="chargePower_kW",
        name="Charge Power",
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.ENERGY,
        value=lambda data: data["charging"]["chargingStatus"].chargePower_kW.value,
    ),
`

**Comment by PaulProjects** [comment]
hm I dont know much about HA but that got changed with https://github.com/mitch-dc/volkswagen_we_connect_id/commit/163adbcce7205b5083b17fa0ca5968605b3d9cfd

**Comment by jonasbkarlsson** [comment]
@mitch-dc, your PR to update HA with requests==2.28.2 did not make it into the 2023.3.0 release. I guess it will be part of 2023.3.1
https://github.com/home-assistant/core/blob/2023.3.0/requirements.txt

**Comment by robinostlund** [comment]
I created this pull request to see if it would be possible to downgrade requests version for weconnect library:
https://github.com/tillsteinbach/WeConnect-python/pull/109

**Comment by mtjoernelund** [comment]
While waiting for either dependency requirements for WeConnect to be downgraded or HA Core to be updated, I just wanted to confirm that manually updating WeConnect to 0.54.1 and making the changes to sensor.py outlined by @robinostlund above seems to be a viable workaround. I have sensors back in HA and so far I have seen no adverse consequences to HA Core.

**Comment by svenkessler** [comment]
> While waiting for either dependency requirements for WeConnect to be downgraded or HA Core to be updated, I just wanted to confirm that manually updating WeConnect to 0.54.1 and making the changes to sensor.py outlined by @robinostlund above seems to be a viable workaround. I have sensors back in HA and so far I have seen no adverse consequences to HA Core.

Thanks for clarification. Did now the same and can confirm, that everything is working now and can't see any downside now.
