### ISSUE TITLE
Problem with updateing/fetching new data after 1 hour

### ISSUE THREAD

**Issue by alecosborne** [mitch-dc/volkswagen_we_connect_id#17]
## Version of the custom_component
v0.0.8.5-dev1

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
hass in docker 
Home Assistant Core 2022.2.2
Home Assistant Operating System 7.2

``

## Describe the bug

I'm having problems with the polling process. After restarting HA, the update process only works for about 1 hour. After that, you can see that there are no more lines in the debug log. When I restart HA or reload the Integration starts to fetch the data again for 1 hour. 
The old integration hasn't that problem.

## Debug log

Finished fetching volkswagen_we_connect_id: data in ... seconds (success: True)

```text

Add your logs here.

```

**Comment by strutings** [comment]
Same problem here. But i can’t figure out if it’s the addon or api at Volkswagen that is causing this.

**Comment by odelma** [comment]
At least I do, this VIN WVWZZZ3CZKEXXXYYY is for a diesel Passat...

**Comment by alecosborne** [comment]
Hi all,

It seems that the polling and status update problem was solved with the last update.

**Comment by mitch-dc** [comment]
Same log messages?

**Comment by strutings** [comment]
Still the same freezing problem. Can't find anything in the log here..

**Comment by doscit01** [comment]
I might have a similiar issue. My instance is starting to loose connection aparently - just found out - but is also able to resync. I've only justed looked and found this log message which appeared multiple times

**Comment by odelma** [comment]
Logs give similar output (nothing special) but I added system monitor sensor and observed this with memory consumption:
![image](https://user-images.githubusercontent.com/10372952/158355034-29e78c02-4790-46be-9715-9dc3422b05e1.png)
There are few restarts first with this integration enabled and memory use shoots pretty fast (less than 10 minutes) to 90+%. At the end there is the situation with this integration disabled and memory consumption stays around 35%.

**Comment by xbouthoorn** [comment]
Is there any improvement on this issue? I see the same behaviour of freezing when using this integration.

**Comment by mitch-dc** [comment]
Not yet, I dont have the same issues.

**Comment by ahochsteger** [comment]
@mitch-dc I've got similar problems that the integration stops working after a while, but maybe I've found the root cause of the problem with an easy fix ...

The log entries show that there is a MemoryError while updating vehicle pictures:
```
Logger: custom_components.volkswagen_we_connect_id
Source: custom_components/volkswagen_we_connect_id/__init__.py:46
Integration: Volkswagen We Connect ID ([documentation](https://github.com/mitch-dc/volkswagen_we_connect_id))
First occurred: 19. April 2022, 07:13:49 (2 occurrences)
Last logged: 19. April 2022, 21:05:10

Unexpected error fetching volkswagen_we_connect_id data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2957, in open
    fp.seek(0)
io.UnsupportedOperation: seek

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 46, in async_update_data
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 175, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 198, in updateVehicles
    self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures,
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 204, in update
    self.updatePictures()
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 353, in updatePictures
    img = Image.open(imageDownloadResponse.raw)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2959, in open
    fp = io.BytesIO(fp.read())
  File "/usr/local/lib/python3.9/site-packages/urllib3/response.py", line 518, in read
    data = self._fp.read() if not fp_closed else b""
  File "/usr/local/lib/python3.9/http/client.py", line 470, in read
    return self._readall_chunked()
  File "/usr/local/lib/python3.9/http/client.py", line 582, in _readall_chunked
    return b''.join(value)
MemoryError
```

The relevant code in the weconnect lib suggests that this feature may be turned off (seems not to be in use for the HA integration anyway) by setting `updatePictures=False`:
https://github.com/tillsteinbach/WeConnect-python/blob/main/weconnect/elements/vehicle.py#L69
Maybe this is an easy fix to improve the stability of the integration.

**Comment by sliepie** [comment]
@ahochsteger  I created a [fork](https://github.com/sliepie/volkswagen_we_connect_id) and implemented the `updatePictures=False`. Could you try that version to test if improves the stability?

When this is a improvement I will create PR to merge this back upstream

**Comment by ahochsteger** [comment]
@sliepie great :)
Since it takes some days for the problem to show up it is not so easy to see if it's really fixed.
Do you know, if I can install the fork besides the other integration thus duplicating the device/entities?

**Comment by ahochsteger** [comment]
@sliepie, nevermind, I was able to install your fork as a separate HACS repo and it replaced the existing one when installing.
This way I think I can easily switch back to the other one when it's merged.
I'll observe it a week or so and will report back.

**Comment by xbouthoorn** [comment]
@sliepie I am running your changes now and it looks like that it's working. Previously my raspberry would crash directly when I activated the integration and now it is already running smoothly for a half a hour.

**Comment by ahochsteger** [comment]
Yes, it's working for me as well, but the memory errors always showed up after some time.

**Comment by joakimberglund** [comment]
> @ahochsteger I created a [fork](https://github.com/sliepie/volkswagen_we_connect_id) and implemented the `updatePictures=False`. Could you try that version to test if improves the stability?
> 
> When this is a improvement I will create PR to merge this back upstream

Yepp works for me also (RPi3B)

**Comment by mitch-dc** [comment]
nice work, if you make a PR i will merge the change! :)

**Comment by mitch-dc** [comment]
Merged the PR

**Comment by xbouthoorn** [comment]
This issue is back after the latest update (0.0.9). That update removes the changes done in the PR.

**Comment by alecosborne** [comment]
For me the bug exits in the current Version too.

**Comment by odelma** [comment]
I also have to add this manually now to prevent my system from crashing due to running out of memory. Was it maybe removed accidentally @mitch-dc?

https://github.com/mitch-dc/volkswagen_we_connect_id/commit/51b4dd5d3965da266a186d57cfa8cafb268020cd#commitcomment-89301823
